### ISSUE TITLE
Question: Functionality similar the core.async/alt

### ISSUE THREAD

**Issue by jamesmintram** [ztellman/manifold#105]
Sorry if this question has been answered before, but I haven't been able to find a way to achieve a "take" from multiple streams in a similar way to core.async/alt.

Is this possible?

**Comment by danielcompton** [comment]
See #102.

**Comment by jamesmintram** [comment]
That looks pretty awesome - and I have seemed to ask at the right time!

Is this likely to end up in a manifold snapshot anytime soon?

**Comment by ztellman** [comment]
This has been merged.
