### ISSUE TITLE
Question: Is cancelling manifold.deferred/future possible?

### ISSUE THREAD

**Issue by jeroenvandijk** [ztellman/manifold#106]
Clojure's `future` has `future-cancel` [[1]](http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/future-cancel) which internally calls `Thread/interrupt` to stop any pending processing where possible. Is there an equivalent for `manifold.deferred/future`? 

Especially if there are nested future's deferred's I can image this to be effective.

**Comment by ztellman** [comment]
Manifold's `future` can be cancelled by putting another value into the deferred it returns.  However, this won't interrupt the thread if the task is already in progress, just refuse to execute once it comes off the queue.
