### ISSUE TITLE
Event Bus Gotcha with ConcurrentHashMap

### ISSUE THREAD

**Issue by lambdahands** [ztellman/manifold#109]
Hey there,

This isn't a bug, but it's a bit of a gotcha that caused some head scratching this morning with the use of `ConcurrentHashMap` and `manifold.bus` [implemented here](https://github.com/ztellman/manifold/blob/master/src/manifold/bus.clj#L82). I was (foolishly) creating topics with a number type that happened to be a `Long`, and when publishing to the bus with a number parsed from JSON, I was unknowingly passing an `Integer`.

This works with Clojure's maps:

``` clj
(get {(int 1) :bar} (long 1))
;; => :bar
```

but `ConcurrentHashMap`s expect a matching value _and_ type:

``` clj
(def m (java.util.concurrent.ConcurrentHashMap.))
(.put m (long 1))
(.get m (int 1))
;; => nil
```

Again, not a bug as this is expected behavior in Java, but I'm wondering if there's somewhere to document this? I can imagine someone else might run into this in the future. If not, feel free to close this, no worries!

**Comment by ztellman** [comment]
This is a tricky little gotcha, and is easily fixed.  Sorry it took so long to get around to this, thank you for the report.
