### ISSUE TITLE
d/future versus clojure.core/future

### ISSUE THREAD

**Issue by malcolmsparks** [ztellman/manifold#11]
If we create a d/chain, containing a single d/future, the semantics of d/chain will mean that a deref on the chain will provide the deref of its 'links'. So for a single deferred link, a deref on the chain causes a deref on the link.

```clojure
(deref (d/chain (d/future (Thread/sleep 1) :ok))) 
=> :ok
```

But if I use a clojure.core future instead, I get a pending future back when I deref the chain.

```clojure
(deref (d/chain (future (Thread/sleep 1) :ok))) 
=> #<core$future_call$reify__6666@6c002f51: :pending>
```

I didn't expect this result, but perhaps there's a good reason for it 

(I'm on beta5)

**Comment by ztellman** [comment]
Fixes for this were sitting upstream of beta5, I've just marked beta6 to officially release them.
