### ISSUE TITLE
put! and put-all! block forever if stream closes

### ISSUE THREAD

**Issue by hadronzoo** [ztellman/manifold#112]
This will never return:

```clojure
(let [str (s/stream)]
  (future (do (Thread/sleep 1000) 
              (s/close! str)))
  @(s/put-all! str (range 100)))
```

If the stream is closed before `put-all!` is called, it returns immediately.

**Comment by ztellman** [comment]
If a stream is closed, that doesn't mean pending puts won't be consumed.  The expectation is if completion of a `put!` is important, then the consumer will always drain the stream, which will result in the realization of the deferred returned by `put!`.

**Comment by hadronzoo** [comment]
Thank you for the clarification. In retrospect that makes complete sense. I spent awhile tracking down a deadlock and this was the cause.

**Comment by hadronzoo** [comment]
So the pending put is conceptually before the close:

```clojure
(let [str (s/stream)]
  (future (do (Thread/sleep 1000)
              (s/close! str)
              (s/take! str)))
  @(s/put-all! str (range 100)))
=> false
```

**Comment by ztellman** [comment]
@hadronzoo that's correct, though I understand why that would be confusing, and if it's causing issues for people using the library I would be willing to consider changing the behavior, since either approach seems reasonable.  Thoughts?

**Comment by hadronzoo** [comment]
I found it unexpected and difficult to figure out what was deadlocked. I had a stream consumer that was closing the stream as a signal to the producer to stop fetching because the messages were no longer needed. It wasn't apparent that the consumer should keep fetching until the `take!` indicated that the stream is closed so that the producer's final `put!` would complete.

Now that I understand the current behavior I think it makes sense that the `close!` follows the current pending `put!`. Perhaps adding a note to the documentation would be a good idea.

Do you have a good strategy for tracking down deadlocks? Do you use timeouts or breakpoints?

**Comment by ztellman** [comment]
The more I think about it, the current implementation is just asking for this sort of thing to happen.  I think it makes sense that `close!` will resolve any pending actions, and `take!` would only see messages that are in the buffer, rather than all the pending puts.

For deadlocks, though, I tend to use https://github.com/ztellman/lein-jammin.

**Comment by DerGuteMoritz** [comment]
> The more I think about it, the current implementation is just asking for this sort of thing to happen.

I just tripped over this behavior, as well. @KingMob WDYT about changing it as suggested by Zach?

**Comment by DerGuteMoritz** [comment]
FWIW, `core.async` behaves the same way as manifold currently does, and intentionally so: https://clojure.atlassian.net/browse/ASYNC-125

**Comment by KingMob** [comment]
@DerGuteMoritz I'm willing to add documentation to clarify, but I don't think we should change the behavior. Doing so will break all code that currently correctly (1) closes, but then (2) still expects to read all pending puts. 

Making this change could cause people to lose data. In theory, if they listen to the deferred returned by `put!`, they'll know their put failed and can handle it. But realistically, they might not have written their code to handle the situation. Not ideal, but ¯\\\_(ツ)_/¯.

Fundamentally, closing in Manifold is for writes, not reads. (Though admittedly, the word "close" suggests it could be closed for both.)

BTW, Netty also works this way. Closing a channel only prevents new writes. All existing data is flushed out normally.
