### ISSUE TITLE
aleph.io/manifold/deferreds.html has a few issues.

### ISSUE THREAD

**Issue by lanejo01** [ztellman/manifold#117]
Two issues that are already fixed in the repo markdown files but not on the webpage itself.

``` clojure
(let [a (future 1)]
  (let-flow [b (future (+ a 1))
             c (+ b 1)]
    (+ d 1))) ;; shouldn't this be c instead of d?
```

Also, there are a lot of nice markdown links but they havent been converted in the html version of the docs on the aleph.io site.
1. At the bottom of http://aleph.io/manifold/deferreds.html go here refers to http://aleph.io/docs/execution.md not http://aleph.io/manifold/execution.html. Also there is a typo on the last line. `Both deferreds and sreams => Both deferreds and streams`
2. http://aleph.io/manifold/streams.html
`Notice that both put! and take! return deferred values.` the link in deferred values goes to http://aleph.io/docs/deferred.md, maybe it should be http://aleph.io/manifold/deferreds.html?

Sorry if this is not the right place to put this issue, I couldn't find anywhere else to put it.

**Comment by ztellman** [comment]
This is the right place, thank you for your reports.

**Comment by ztellman** [comment]
I've updated the site generation so that it pulls in the latest documentation changes, and the site should now reflect all the appropriate fixes.
