### ISSUE TITLE
map is causing the stream to hang

### ISSUE THREAD

**Issue by RasterBurn** [ztellman/manifold#12]
For some reason this hangs (not the use of `s/map`):

```clojure
> (->> [1 1 1 2 2 3] 
       s/->source
       (s/partition-by identity)
       (s/map s/stream->seq)
       (s/stream->seq)
       (println))
```

I would it expect it to print:

```clojure
((1 1 1) (2 2 2) (3))
```

But using `s/mapcat` seems to be ok:

```clojure
> (->> [1 1 1 2 2 3] 
       s/->source
       (s/partition-by identity)
       (s/mapcat s/stream->seq)
       (s/stream->seq)
       (println))

(1 1 1 2 2 3)
nil
```

**Comment by ztellman** [comment]
So partition-by is a little tricky; it doesn't return a stream of seqs, but a stream of streams.  This means that each sub-element is *lazy*, you can't get to the second element of the sequence until you fully realize it.

This will do what you want:

```clj
(->> [1 1 1 2 2 3] 
       s/->source
       (s/partition-by identity)
       (s/map s/stream->seq)
       (s/stream->seq)
       (map doall)
       (println))
```

I've been bitten by this too, and am considering making `s/partition-by` work more like its `clojure.core` equivalent, and have the current function be called `lazily-partition-by` or something.

**Comment by RasterBurn** [comment]
Thanks!
