### ISSUE TITLE
Mention manifold-cljs somewhere

### ISSUE THREAD

**Issue by dm3** [ztellman/manifold#122]
@ztellman: Not sure if you were aware - I've done a [Cljs port of Manifold](https://github.com/dm3/manifold-cljs). It's pretty complete, except for the `let-flow` macro. However, I haven't been using it for anything serious. I doubt anyone else has either.

Do you think it's worth linking to the port from the Manifold project?

**Comment by vspinu** [comment]
I am just curious. Would it make more sense to build instead a lightweight version of manifold on top of core.async and thus automatically cross-host?

**Comment by dm3** [comment]
@vspinu It would probably work. Never thought about that :) However maintaining semantic equivalence might be a much harder task than what I did - literally copy-pasting 80% of the source code.

**Comment by ztellman** [comment]
Hi, I apologize for never responding to this issue.  I'm happy to accept a change to the README which adds a link at the bottom.

**Comment by kachayev** [comment]
@ztellman This issue was resolved already with #134, so we can close it.
