### ISSUE TITLE
take on a drained deferred source doesn't return nil

### ISSUE THREAD

**Issue by RasterBurn** [ztellman/manifold#13]
Let me dissect that a bit.

I created a stream from a manifold.deferred.

When I call `take` on the stream initially, it returns the value of the deferred (which is expected) and the stream is drained (also expected).

But then, when I call `take` again, it should return `nil` which it doesn't.  Here's a sample repl session:

```clojure
=> (def z (d/deferred))
'z
=> (def a (s/->source z))
'a
=> (d/success! z 42)
true
=> (s/drained? a)
false
=> @(s/take! a)
42
=> (s/drained? a)
true
=> @(s/take! a)

ClassCastException java.lang.Boolean cannot be cast to java.util.concurrent.Future  clojure.core/deref-future (core.clj:2180)
```

The reason I even came across this is that I was hoping that the deferred which is returned from `manifold.stream/reduce` could be used in a pipeline transparently.  This is a trivial example of what I was wishing to do:

```clojure
(->> (range 10)
     s/->source
     (s/reduce +)
     s/->source)
```

**Comment by ztellman** [comment]
Thanks for the report, I implemented deferred sinks as a bonus:

```clj
user> (require '[manifold.stream :as s] '[manifold.deferred :as d])
nil
user> (def d (d/deferred))
#'user/d
user> (s/connect [1 2 3] d)
nil
user> d
<< 1 >>
```
