### ISSUE TITLE
Please regenerate official docs

### ISSUE THREAD

**Issue by ehashman** [ztellman/manifold#132]
The [published documentation](http://aleph.io/codox/manifold/) currently corresponds to manifold 0.1.1-SNAPSHOT, but the latest stable release is 0.1.6.

**Comment by ztellman** [comment]
Oh, hmm.  That should be happening automatically, I'll look into why it
isn't.

**Comment by ztellman** [comment]
Should be fixed now, thanks for the report.

**Comment by ehashman** [comment]
Thanks for the update! However, it now appears to be tracking 0.1.5-alpha1. Is it possible to make the latest docs available?

**Comment by ztellman** [comment]
Sigh, the documentation generation apparently changed what folder it writes to between versions.  I fixed that, too.  Thanks again.

**Comment by ehashman** [comment]
No problem, thanks for fixing :grin:
