### ISSUE TITLE
connect-via-async?

### ISSUE THREAD

**Issue by derwolfe** [ztellman/manifold#133]
I recently wrote a system that required a bit of concurrency control - I started using `manifold.stream/batch` and `manifold.stream/connect-via`. Part way through the implementation I noticed that connect-via wasn't providing backpressure for the callback function. This confused me a bit. I ended up rewriting this using `consume-async`. 

Would you have interest in a `connect-via-async` function that functions similarly to `consume-async`? Or does it sound like I've likely just composed some of manifold's functionality incorrectly :)

As a reference, the code I've been working on is available at https://github.com/derwolfe/az-manifold/blob/31ddbed78117baca83a2cf29dbd99e78354cf5a8/src/az_manifold/core.clj

**Comment by ztellman** [comment]
That's odd, connect-via should provide back pressure. Certainly much of
Manifold's implementation relies on that. Can you provide an example of it
not doing so?

**Comment by derwolfe** [comment]
Sorry Zach, I think I misused the term backpressure.. connect via definitely provides back pressure when the output stream is blocked, it just isn't waiting the deferred to be realized. The difference I'm looking for is a version of connect via that is able to wait to on a deferred having been realized, similar to the difference between consume and consume-async. I'll modify my example code to show what I mean once I get back home 😀.

**Comment by derwolfe** [comment]
Not sure how I made my original mistake! However, on rewriting the code that I'd originally envisioned using `connect-via`, it all works as expected. Sorry for the nonsense issue!

**Comment by ztellman** [comment]
No worries, glad to hear that the foundations of the library aren't wrong somehow.
