### ISSUE TITLE
transducer completion state going missing

### ISSUE THREAD

**Issue by mccraigmccraig** [ztellman/manifold#146]
i thought the third `take!` should return `{:foo 30 :bar 30}` - or am i misunderstanding something ?

```
er-model.system> (def s (manifold.stream/->source [{:foo 10 :bar 10} {:foo 20 :bar 20} {:foo 30 :bar 30}]))
#'er-model.system/s
er-model.system> (def t (manifold.stream/transform (partition-by :foo) s))
#'er-model.system/t
er-model.system> @(manifold.stream/take! t)
[{:foo 10, :bar 10}]
er-model.system> @(manifold.stream/take! t)
[{:foo 20, :bar 20}]
er-model.system> @(manifold.stream/take! t)
nil
```

**Comment by ztellman** [comment]
No, that seems to be the appropriate behavior:

```clj
> (transduce (partition-by :foo) conj [] [{:foo 10 :bar 10} {:foo 20 :bar 20} {:foo 30 :bar 30}])
[[{:foo 10, :bar 10}] [{:foo 20, :bar 20}] [{:foo 30, :bar 30}]]
```

I'll look at how Manifold handles transducers and see if I can identify the issue.

**Comment by ztellman** [comment]
Hi, this was fixed a few months back in https://github.com/ztellman/manifold/pull/136, but I haven't pushed out a new release since then.  If you target `[manifold "0.1.7-alpha6"]` everything should work as expected.
