### ISSUE TITLE
Question: How do I send multiple sources to a single sink?

### ISSUE THREAD

**Issue by RasterBurn** [ztellman/manifold#15]
I have two source streams and a single sink which writes to a file.

When stream A closes, it closes the sink and stream B doesn't finish writing.

I see I can provide `{:downstream? false}` on A, but doesn't that introduce a race condition?  What if B happens to finish first?

**Comment by RasterBurn** [comment]
More details I see I failed to include:

I'm using `connect` like so:

```clojure
(s/connect A sink)
(s/connect B sink)
```

Also, my topology is actually diamond shaped:

```
    A
in < > sink
    B
```

**Comment by ztellman** [comment]
Broadly, I'd suggest something like this:

```clj
(require 
  '[manifold.deferred :as d]
  '[manifold.stream :as s])

(defn closed-deferred [s]
  (let [d (d/deferred)]
    (s/on-closed s #(d/success! d true))))

(defn connect-all [srcs dst]
  (doseq [s srcs]
    (s/connect s dst {:downstream? false}))
  (d/chain (->> srcs (map closed-deferred) (apply d/zip))
    (fn [_] (s/close dst)))
```

**Comment by RasterBurn** [comment]
Awesome... thanks! :+1:
