### ISSUE TITLE
Should clojure.core futures be sourceable?

### ISSUE THREAD

**Issue by benmoss** [ztellman/manifold#20]
I see that manifold.deferred futures are (via `->source`), but regular Clojure ones are not. Was this intentional? I'd be happy to try to make a patch if not.

**Comment by ztellman** [comment]
Deferreds are sourceable, you can do (-> x ->deferred ->source) to get your
desired outcome.  I need to give some thought as to whether anything which
is coerceable to a deferred should automatically be coerceable to a stream.

**Comment by ztellman** [comment]
I think this would be more confusing than helpful, so I'm going to close this as "wontfix".
