### ISSUE TITLE
:scheme type inconsistency?

### ISSUE THREAD

**Issue by lvh** [ztellman/manifold#23]
When making requests, the request map requires the scheme to be a str; otherwise https://github.com/ztellman/aleph/blob/0.4.0/src/aleph/http/client.clj#L65 fails. When receiving a request, the request map passed to the handler has `:scheme` as a keyword:

```
2015-Feb-20 15:29:13 -0800 zygalski.local DEBUG [shimmer.core] - incoming-request {:remote-addr 0:0:0:0:0:0:0:1, :headers {host localhost:7467, user-agent curl/7.37.1, accept */*}, :server-port 7467, :keep-alive? true, :uri /, :server-name localhost, :query-string nil, :body nil, :scheme :http, :request-method :get}
```

I'm not sure if this is intentional, or an unintentional inconsistency.

**Comment by ztellman** [comment]
I think you mean to put this in the Aleph project.  This was unintentional, and has been fixed by https://github.com/ztellman/aleph/commit/3a8a02b46ae7df6c733c26d3853cb03860a3ca27.

**Comment by lvh** [comment]
Indeed I did! My apologies, this (using aleph) was my first time really doing anything with manifolds, so I had both open in my browser, and picked the wrong one :) Thanks for resolving the issue, and thanks for writing all of this cool software!
