### ISSUE TITLE
Allowing return of deferred values from catch?

### ISSUE THREAD

**Issue by bts** [ztellman/manifold#24]
Hey Zach,

What are your thoughts on allowing the return of deferred values from `d/catch`? Currently deferreds from `d/catch` aren't "flattened" as they are with `d/chain` and friends. e.g.:

```clojure
user=> (d/catch (d/error-deferred (Exception.)) (fn [e] (d/success-deferred :delayed-recovery)))
<< << :delayed-recovery >> >>
```

I find myself wanting to do this so that I can catch errors while in a `d/loop`, and `d/recur` once I've recovered (asynchronously) from the error (e.g., performing a "cooldown" sleep before recurring.)

Thanks,
Brian

**Comment by ztellman** [comment]
I think flattening out values from `catch` via unwrap seems like a good idea, I think that's just an oversight on my part.  Pull request welcome, or I can take care of it myself.

**Comment by bts** [comment]
I just saw your response a few minutes ago and started to take a look. You beat me to it -- thanks for implementing this!
