### ISSUE TITLE
Clarification on semantics of drained?

### ISSUE THREAD

**Issue by dparis** [ztellman/manifold#26]
Based on the stream documentation, the semantics of the `drained?` function are described as:

> Sources that will never produce any more messages (often because the corresponding sink is closed) is said to be drained. We may check whether a source is drained via drained? and on-drained.

I read this to mean that a source which is both closed, and which also has no pending puts, i.e. it will never produce another message because no more can be added and all pending have been taken.

However, this is the behavior I'm seeing:

```clojure
(def a (ms/stream))

(ms/put! a 123)
(ms/put! a 123)

(ms/close! a)

a  ;; << stream: {:pending-puts 2, :drained? true, :buffer-size 0, 
   ;;             :permanent? false, :type "manifold", :sink? true, :closed? true, 
   ;;             :pending-takes 0, :buffer-capacity 0, :source? true} >>

@(ms/take! a)   ;; 123
@(ms/take! a)   ;; 123
@(ms/take! a)   ;; nil
``` 

I would expect that `closed?` would retrurn `true` immediately after the called `close!` is resolved, but `drained?` would only return true after the second call to `take!` has been resolved.

Am I understanding the intent correctly?

**Comment by ztellman** [comment]
Yes, you were correct in your understanding.  There was an issue in how the `drained?` check worked for streams with no buffer, this should be resolved in the latest snapshot.

**Comment by dparis** [comment]
Great, thanks Zach!
