### ISSUE TITLE
Possible bug on default stream take timeout

### ISSUE THREAD

**Issue by dparis** [ztellman/manifold#28]
I've been digging through the logic of the `take` implementation in `default.clj` while debugging #27. Possible I found an unrelated bug on https://github.com/ztellman/manifold/blob/master/src/manifold/stream/default.clj#L176:

```clojure
;; add to the consumers queue
(if (and timeout (<= timeout 0))                      ;; Should be (>= timeout 0) here?
  (d/success-deferred timeout-val executor)
  (let [d (d/deferred executor)]
    (d/timeout! d timeout timeout-val)
    (let [c (Consumer. d default-val)]
      (if (.offer consumers c)
        d
        c))))
```

Unless I'm missing something (very possible!) a valid `timeout` value should always be some positive integer. As such, `timeout` will never validly evaluate to <= 0, and this `and` will always hit the false path.

**Comment by ztellman** [comment]
Okay, i just took a closer look at this.  Typically a timeout is positive, but if it's <= 0, then the timeout has elapsed and it short circuits.  In other words, this is as intended.
