### ISSUE TITLE
Possible race condition when using future-with and dirigiste executor?

### ISSUE THREAD

**Issue by dparis** [ztellman/manifold#30]
After tearing my hair out for a bit tracking this down, I think I've narrowed it to the `util/future-with` macro when using an `Executor` instance returned by dirigiste . A basic sometimes-repro case goes like this:

```clojure
(dotimes
 [n1 100]
 (let
  [e (exec/fixed-executor 5)]
  (dotimes
   [n2 5]
   (md/future-with e (println (str "inside worker " n1 ":" n2))))
  (.shutdown e)))
```

More often than not, this will throw a `java.util.concurrent.RejectedExecutionException` at [Executor.java:299](https://github.com/ztellman/dirigiste/blob/master/src/io/aleph/dirigiste/Executor.java#L299). I installed a custom build of dirigiste with some additional logging output which traces the values of `numWorkers` and `numThreads`/`maxThreadCount` in Executors.java, and in both the `fixedController` and `utilizationController` implementations of `shouldIncrement` I was seeing an additional erroneous call with `numWorkers` failing the less-than inequality check.

If I had to guess, I'd say something funky is happening with the thread-binding management within the `future-with` macro. Maybe there's some non-threadsafe mutable state lurking in the Executor implementation logic?

Let me know if there's anything I can do to further help debug this. If it turns out the bug is a dirigiste issue rather than manifold, feel free to close this and I'll re-open the issue over on that project.

**Comment by ztellman** [comment]
Okay, so in a `fixedExecutor` the workers are all spun up at instantiation via the `initialThreadCount` parameter, but the fact that they're started up doesn't mean that they've gotten to reading from the queue yet.  If you immediately try to put a bunch of stuff onto the executor, it's very possible that you'll "win" that race.

I'm not sure I'd consider this a bug, but I'm willing to have a deeper discussion if you feel differently.  Did you come across this bug in a production use-case, or in a test case that immediately uses the executor upon instantiation?

**Comment by dparis** [comment]
Ah, fair enough. I wasn't aware there was any timing involved in the availability of the threads from the executor. In production it's doubtful that the `future-with` call is going to be made so quickly after the executor is instantiated, but it was failing my unit tests when I triggered the call almost immediately after. Here's a simplified version of what I'm doing:

```clojure
(defn start-worker
  [input-stream thread-count target-utilization]
  (let [e (exec/utilization-executor thread-count target-utilization)]
    (doto (Thread. (fn []
      ;; Loop on stream take! msg from input-stream
      (when msg (md/future-with e (some-blocking-fn msg)))
      ;; Loop ends when take! returns nil on stream closed, executor is shutdown
)))))
```

Essentially I want watch an input-stream and execute some I/O blocking functions within futures to process the messages received. Since I'm expecting the message traffic to be very bursty, it would be nice to have the thread executor scale the pool down during lulls in activity. I'd also like all of the thread management housekeeping to be abstracted, hence creating the executor within the function body's let scope and having the futures close over it.

Is there a method to determine the executor's availability? I already have some clojure wrapper functions around dirigiste's constructor methods, I could just have the wrappers ensure the executor is ready before returning or delivering a deferred, etc.

Also, if there's a better CSP pattern to accomplish the kind of stream processing I'm describing, I'd be happy to improve my implementation.

**Comment by ztellman** [comment]
Honestly, if you're okay with the sixty second idle timeout on Clojure's `future` pool, you could just use that.  It has the benefit/drawback of being unbounded, which appears to be what you want here.  Likewise, you could just put a large-ish queue in front of the executor, which would shield you from these sorts of timing issues.

**Comment by dparis** [comment]
That's not unreasonable. In production, I doubt it would be an issue anyway, and now that I know what's going on I can avoid that case in my unit tests. 

I don't think I need anything else. Thanks for responding, Zach, I appreciate your time!
