### ISSUE TITLE
chain should document error behavior

### ISSUE THREAD

**Issue by lvh** [ztellman/manifold#41]
One of deferred's critical features is that it knows how to represent errors. However, chain, one of the most common tools (at least for me) for working with deferreds, doesn't document what happens when its input deferred contains an error, or any of the intermediate fns raises.

**Comment by ztellman** [comment]
I'm not sure if this was already here when the issue was opened, but the documentation now clearly states:

```
If any stage in chain throws an exception or returns a deferred that yields an error, all subsequent stages are skipped, and the deferred returned by chain yields that same error. To handle these cases, you can use manifold.deferred/catch:
```
