### ISSUE TITLE
[Question] How to properly release resource on closed/drained?

### ISSUE THREAD

**Issue by ddossot** [ztellman/manifold#43]
I have the following connection between an Aleph websocket sink and a bus source:
```clojure
  (s/connect
    (s/filter
      (partial
        room-accept-event?
        idempotent-filter)
      (bus/subscribe
        chatrooms room))
    socket)
```
I wanted to check if the `FIFOCache` instance that's wrapped in `idempotent-filter` was collected after the socket disconnects.

Before that, I've added `on-drained` and `on-closed` listeners on the above to track streams events. Things look great: I see the `socket` close event immediately followed by the drained event from `s/filter`, followed by the drained event from `bus/subscribe`.

But when I inspect a heap dump (after GC) I see that there are still references maintained on the object I'm concerned about:

![screenshot from 2015-07-22 17 31 08](https://cloud.githubusercontent.com/assets/119028/8840571/de5edc1e-3097-11e5-9ab7-4de046bbd915.png)

I'm concerned this could be a memory leak. This could also be a complete PEBKAC, whether I misinterpreted the heap dump or I forgot to perform a necessary clean-up on the streams to release related resources (I've tried `{:upstream? true}` but to no avail). I've also tried removing the filter and in that case, the `FIFOCache` instances are GCed away as expected.

Thanks for any light you can shed on this, even if it's for exposing my n00bness :sweat_smile:

**Comment by ztellman** [comment]
Currently, when a sink is closed, the graph will only realize that once they've tried (and failed) to put a message into it.  This can definitely become a problem if there are lots of connections and few messages, and I may try to do something a bit more eager, but in the meantime adding an `on-closed` callback that closes the stream returned by `subscribe` will have the desired effect.

Sorry for any time spent tracking this down in memory dumps, I know that can be pretty tedious.  Let me know if you have any other questions.

**Comment by ddossot** [comment]
Super happy to confirm it works as you said :dancers: 

I didn't know it was OK to call `close!` on a source. The doc says:
> Closes an event sink, so that it can’t accept any more messages.

so I was wrongly convinced closing the source created by `bus/subscribe` wouldn't work :doh:

**Comment by ztellman** [comment]
Yeah, both sinks and sources can be closed, I'll update the documentation to reflect that.
