### ISSUE TITLE
manifold.stream creates dependency cycles

### ISSUE THREAD

**Issue by cursive-ghost** [ztellman/manifold#5]
I'm not sure if this is technically a bug or not, but I thought it warranted discussion. Cursive includes functionality to check for dependency cycles in namespaces, and will produce an error when the user tries to load a namespace involved in a cycle, the assumption being that they just created it inadvertently. For a while there, the entire transitive closure of dependencies of the file being loaded was calculated and cycles anywhere in the graph were warned about. I've since fixed this, but while that was the case several users reported problems with `manifold.stream`. This is used from `manifold.stream.core, .queue, .seq, .deferred, .async` but also requires them itself later in the file. This will cause problems for people wanting to work on the manifold source with Cursive, and seems weird - can it be fixed?

**Comment by cursiveclojure** [comment]
BTW it looks like this might actually be considered a problem as of 1.7 alpha 5: https://groups.google.com/d/msg/clojure/jj87-4yVlWI/OjigPR3tIEcJ

**Comment by neverfox** [comment]
I'm running into this again now that I've upgraded to Cursive 1.2.1 and IDEA 2016.1 (Clojure 1.8). The message is `Dependency cycle: time.clj -> time.clj`. I'll cross-post to Cursive.

**Comment by ztellman** [comment]
I think what I'm doing in `manifold.time` is valid, but let me know if Colin feels differently.

**Comment by neverfox** [comment]
Will do. Looks like someone already reported it over there.

**Comment by cursive-ide** [comment]
I would say it's valid but tricky :-) I think this is a Cursive bug, I've worked around it for now and I'll think about a better solution.

**Comment by neverfox** [comment]
@cursive-ide Colin, is the workaround something one can do for themselves by how the code is written? As it is now, this is a showstopper on all of my manifold-based code.

**Comment by cursive-ide** [comment]
@neverfox There's a workaround in cursive-ide/cursive#1298: Disabling "Load out of date file dependencies transitively" eliminates the error.

**Comment by neverfox** [comment]
@cursive-ide Missed that sentence. Thanks. Are there any negative side-effects to disabling that?

**Comment by cursive-ide** [comment]
@neverfox I'll comment over there since this is Cursive related, not manifold related.
