### ISSUE TITLE
error values sometimes unexpectedly becoming success values

### ISSUE THREAD

**Issue by mccraigmccraig** [ztellman/manifold#54]
it seems `manifold.deferred/catch` can transform error values into success values (rather than returning the value of the error handler) in some circumstances. perhaps if the erroring deferred is already realized when given to the catch (though i haven't taken any steps to validate this hypothesis)

```
;;  [manifold "0.1.1-alpha4"]
(require '[manifold.deferred :as d])

(->
 (d/chain (d/success-deferred :boo)
          (fn [v] (throw (ex-info "boo" {})))
          (fn [v] (prn "hi")))
 (d/catch (fn [e]
            (prn "error")
            :caught))
 deref)

;; as expected - prints "error", returns :caught

(->
 (d/chain (d/error-deferred :boo)
          (fn [v] (prn "hi")))
 deref)

;; as expected - explodes

(->
 (d/chain (d/error-deferred :boo)
          (fn [v] (prn "hi")))
 (d/catch (fn [e]
            (prn "error")
            :caught))
 deref)

;; whoa - doesn't print error, returns :boo

(->
 (d/chain (d/error-deferred :boo)
          (fn [v] (prn "hi")))
 (d/catch (fn [e]
            (prn "error")
            :caught))
 (d/chain (fn [v]
            v))
 deref)

;; returns :boo, so the error value has unexpectedly become the success value
```

**Comment by dm3** [comment]
If you look https://github.com/ztellman/manifold/blob/master/src/manifold/deferred.clj#L938, not specifying a `catch` exception type will default to `Throwable`. Later on the error value is matched against the type being caught. The error handler only runs when the type matches.

```clojure
(->
 (d/chain (d/error-deferred :boo)
          (fn [v] (prn "hi")))
 (d/catch clojure.lang.Keyword 
       (fn [e]
            (prn "error")
            :caught))
 deref)

error
=> :caught
```

**Comment by mccraigmccraig** [comment]
ah, so you can catch non-Throwable types too... that works

```
(->
 (d/chain (d/error-deferred :boo)
          (fn [v] (prn "hi")))
 (d/catch clojure.lang.Keyword
     (fn [e]
       (prn "error")
       :caught))
 deref)
;; => prints "error", returns :caught
```

**Comment by mccraigmccraig** [comment]
still seems like odd semantics though, that the catch of Throwable stops the error propagating and turns the error-value into a success-value - should it not let the uncaught error continue to propagate ?

**Comment by ztellman** [comment]
Yes, that is exactly what should be happening.  Commit forthcoming.
