### ISSUE TITLE
batch fails to exert back-pressure when downstream streams close

### ISSUE THREAD

**Issue by hadronzoo** [ztellman/manifold#55]
In the following case one would expect blocking `put!`s to stream `a` to wait forever after one has exceeded the batch size:

```clojure
(ns test.batch
  (:require [manifold.stream :as s]))

(def a (s/stream* {:permanent? true}))
(def b (s/batch 10 a))
(def c (s/stream))

(s/connect b c)
(s/close! c)

(time (dotimes [_ 10000] @(s/put! a :test)))
;; "Elapsed time: 45.356857 msecs"
```

If `c` is not closed, `put!`s to stream `a` will eventually stop completing, as expected.

**Comment by ztellman** [comment]
If `c` is closed, then `b` will be closed.  I'd expect that your `put!` calls are returning false, in this case.

**Comment by ztellman** [comment]
Oh, I'm sorry, I missed the `permanent?` flag.  Let me look into this.

**Comment by hadronzoo** [comment]
Thanks!
