### ISSUE TITLE
deffered/chain doesn't appear to be emitting exceptions

### ISSUE THREAD

**Issue by doubleagent** [ztellman/manifold#62]
Hopefully I haven't made a simple mistake here:

![image](https://cloud.githubusercontent.com/assets/56522/12754797/4d38b9dc-c992-11e5-9917-a9de9db3fc23.png)

This also prevents catch from working.  I am using the version which comes with Aleph, 0.4.1 beta-3. Clojure 1.7.0.

**Comment by ztellman** [comment]
`success!` won't throw an exception if it causes one further down in a deferred callback.  Rather, it will just put the deferred into an error state.  If you type `*2` into the REPL after the steps provided here, you'll see the exception.  I'll look at how to make this more clear in the documentation.

**Comment by doubleagent** [comment]
Can you help me understand how this portion of the wiki is intended to work now?

![image](https://cloud.githubusercontent.com/assets/56522/12763952/d2e36ada-c9bc-11e5-967d-0d573055c209.png)

**Comment by ztellman** [comment]
Sure.  `(-> d (d/chain #(/ 1 %))` returns a deferred which will yield the result of `#(/ 1 %)`, which can either be a value or an exception.  `d/catch` will "catch" a deferred which yields an exception, and return a deferred representing the value returned by its handler (in this example, `nil`).  

I can see how this is a little confusing in my example, since I rely on side effects.  But where `d/success` is called, you see that `true` is returned, and "whoops ..." is printed out by the catch handler.

**Comment by doubleagent** [comment]
Hopefully you can see my confusion.  If I understand you correctly, the example will print out "whoops..." and the value of d will be nil.  Why don't I see this?

![image](https://cloud.githubusercontent.com/assets/56522/12764775/29267730-c9c1-11e5-9220-dcb0a6d112d1.png)

**Comment by ztellman** [comment]
You're looking at the result of the original deferred, not the deferred returned by `chain`.

```clj
user> (require '[manifold.deferred :as d])
nil
user> (def d1 (d/deferred))
#'user/d1
user> (def d2 (d/chain d1 #(/ 1 %)))
#'user/d2
user> (d/success! d1 0)
true
user> @d1
0
user> @d2
ArithmeticException Divide by zero  clojure.lang.Numbers.divide (Numbers.java:158)
user> 
```

**Comment by ztellman** [comment]
Oh, and you're not seeing the output of your println because `catch` expects a function that takes one argument, and yours takes zero arguments.

**Comment by doubleagent** [comment]
Thanks for being patient with me.  I can be a dumbass sometimes.

**Comment by ztellman** [comment]
No worries.  I need to check why you're not seeing some sort of logged error due to the arity mismatch, I'm sure you're far from the only person who's made that mistake.

**Comment by doubleagent** [comment]
d2 emits the arity mismatch exception when dereferenced.

**Comment by doubleagent** [comment]
I wasn't reading closely enough and missed that chain returns a deferred.  Even one example of `(def d2 (d/chain d1 ...))` would have cleared up my confusion.
