### ISSUE TITLE
bus publish returns true even if only subscribed consumer doesn't receive the message

### ISSUE THREAD

**Issue by alvatar** [ztellman/manifold#65]
The documentation says that `bus/publish!` *publishes a message on the bus, returning a deferred result representing the message being accepted by all subscribers.*
That's not what I could see from testing it: if an external consumer fails to receive a message, that function still returns a deferred `true`.

**Comment by ztellman** [comment]
What do you mean by "fails to receive the message"?  Is the consumer blocked?  Closed?

**Comment by alvatar** [comment]
Yes, closed. Or just kill the process holding the socket too.

**Comment by ztellman** [comment]
If a subscriber is closed, it's not considered a subscriber anymore.  `publish!` will return `false` if there are no registered subscribers, or `true` once all active subscribers have accepted the message.  If you can give me a bit of context on what you're trying to accomplish, I can try to suggest an alternative.

**Comment by alvatar** [comment]
Thanks @ztellman. I'm trying to make my server aware of the message arriving to *at least* one destination (*all* semantics, that's even better).
In my particular test, if I use a single subscriber and it doesn't receive the message (it's closed), the function is returning `true`, but I would expect `false`. Isn't that the case?

My target here is to make a tiny notifications service that receives request to send messages to clients using a regular HTTP endpoint. These clients register themselves using a user-id, which I set up as a topic (so a user can connect from multiple devices). I need to be able to tell whether the notification was delivered to at least one of the subscribers.

**Comment by ztellman** [comment]
```clj
manifold.bus> (def b (event-bus))
#'manifold.bus/b
manifold.bus> (publish! b :foo 1)
<< false >>
manifold.bus> (def s (subscribe b :foo))
#'manifold.bus/s
manifold.bus> (publish! b :foo 1)
<< … >>
manifold.bus> @(s/take! s)
1
manifold.bus> *2
<< true >>
manifold.bus> (s/close! s)
nil
manifold.bus> (publish! b :foo 1)
<< false >>
```

This seems to be working as expected.  Maybe double-check that there are no subscribers via `manifold.stream/downstream`?

**Comment by alvatar** [comment]
The subscriber is still there after I both kill the process or close the websocket from the subscriber side.
So that socket wasn't cleaned properly (a faulty/incomplete implementation of the client I'm using? -- it is just a chrome extension), but still, shouldn't it return `false` since the subscriber isn't receiving it?

**Comment by ztellman** [comment]
How is the subscriber attached to the websocket connection?  Propagation of closing between connected streams isn't immediate, if A is connected to B and B is closed, we'll have to try to `put!` a message into B before we close A.  Maybe that's the issue?

**Comment by alvatar** [comment]
Yes, it happens like that. If you send a message to A, and A is closed, first time it will return `true`, second time will return `false`. Is this expected?
However, with this model, there is no way of knowing that the message has arrived, right? The meaning of true is just *it sucessfully tried to deliver* , not *it was delivered and acknowledged*. I would find the second more useful, especially for my purpose, where I would need to build my own message acknowledgment on top of websockets. Is aleph capable to do acknowledge that the subscriber received the message successfully somehow?

**Comment by ztellman** [comment]
In any queue representation I'm aware of, a put is successful if the message is now on the queue.  That doesn't provide any guarantees about what happens downstream of the queue, because there's supposed to be a separation of concerns.  

To solve your initial problem, you can just do `(s/on-closed websocket-conn #(s/close! subscriber))`.  To solve your more general problem, you can define a bus with a stream-generator that just calls `(manifold.stream.Callback. f nil nil)`, where f calls `put!` on the websocket connection and returns the result of `take!` for the ACK.  Be sure that this is what you want, though, because this means that the throughput of your publish system is bounded by the slowest client that's connected to you (some mobile phone going through a tunnel, for instance).  You'll likely want to use `try-put!` and `try-take!` with some well-thought-out timeouts.

**Comment by alvatar** [comment]
Thank you @ztellman, I'll try that.
