### ISSUE TITLE
0.1.4-alpha1 - stream/put! return nil, rather than true or false

### ISSUE THREAD

**Issue by zentrope** [ztellman/manifold#67]
I updated to aleph `0.4.1-beta6`, which pulls in manifold `0.1.4-alpha1`.

On the old case:

```clojure
(defn- send!
  [socket data]
  (let [rc @(stream/put! socket (codec/encode data))]
    (log/info "RC:" rc)
    rc))
```

This function (socket == websocket stream) returns `true` or `false` if the message makes it through.

With `0.1.4-alpha`, it now returns nil.

Bug?

**Comment by ztellman** [comment]
Yes, that isn't the expected behavior.  I'll look into it.

**Comment by ztellman** [comment]
Just to get a bit more detail, where are you getting `socket` from?

**Comment by zentrope** [comment]
I detect the problem on the "client" side, using `http/websocket-client`.

```clojure
(defn create-client
  [config]
  @(http/websocket-client (-> config :uri) {:insecure? false}))
```

Not sure that helps!

**Comment by zentrope** [comment]
A little more context: I acquire that connection to an Aleph server running on the other side. I then spawn that into a go-loop where I block on `(@stream/take! ...)` and then process messages when the come in.

I also spawn a differen go-loop which listens for changes to a database (basically), and publishes a message when it detects a change, using `@(stream/put! ...)`.

Finally, yet another process in the system calls a function on this component to also do a put on the stream.

All processes call the same basic function (quoted above).

**Comment by ztellman** [comment]
This isn't an issue in Manifold, but rather in the Aleph code which presents Netty futures as Manifold deferreds.  This is fixed by https://github.com/ztellman/aleph/commit/0f844884bd489b76a4cc96bc60d9ec3c3e3f4856, which will be included in a new beta release soon.

**Comment by zentrope** [comment]
Thanks! I updated to `aleph-0.4.1-beta7` and the problem is resolved.
