### ISSUE TITLE
Unable to build documentation

### ISSUE THREAD

**Issue by lvh** [ztellman/manifold#68]
On a fresh checkout of manifold, `lein codox` fails due to a missing plugin (`'codox' is not a task. See 'lein help'.`). I don't know if that's intended to work, but there's a codox in plugins, so I'm guessing it is. I was able to build the documentation by switching codox to lein-codox and updating the version to something available on Clojars as follows:

```
diff --git i/project.clj w/project.clj
index a2dc4d3..5cb811b 100644
--- i/project.clj
+++ w/project.clj
@@ -16,7 +16,7 @@
                    :benchmark :benchmark
                    :stress #(or (:stress %) (= :stress (:tag %)))
                    :all (constantly true)}
-  :plugins [[codox "0.8.10"]
+  :plugins [[lein-codox "0.9.4"]
             [lein-jammin "0.1.1"]
             [ztellman/lein-cljfmt "0.1.10"]]
   :cljfmt {:indents {#".*" [[:inner 0]]}}
```

(after which lein codox worked fine)

**Comment by lvh** [comment]
I came across this because I wanted to help make docs build automatically, but since the docs are served by Aleph I'm guessing there on a server where Travis is unlikely to be able to do that for you :)

**Comment by lvh** [comment]
(Also it looks like https://ztellman.github.io/manifold/ is current but http://aleph.io/codox/manifold/ is not)

**Comment by ztellman** [comment]
I use `lein doc` to run Codox.  Does that not work for you?  I'm not sure why the documentation is out of date, looking at that now.

**Comment by ztellman** [comment]
Okay, it was an issue with my script to push the changes.  Everything should be up to date now.

**Comment by lvh** [comment]
Is that an alias?

```
lvh@zygalski ~/P/manifold (master)> lein doc                                                                20:35:54
'doc' is not a task. See 'lein help'.
```

**Comment by ztellman** [comment]
Oh, I think I get it.  Look at the "breaking changes in 0.9" at https://github.com/weavejester/codox.

**Comment by lvh** [comment]
Oh, man. I'm doing a pretty good job opening shitty tickets today :D So, what do we do; update codox anyway (hopefully not breaking too many scripts), I'll add some docs describing how to build the documentation?

**Comment by ztellman** [comment]
Sure, go ahead and update the dependencies, and I'll update my local "push" scripts.

**Comment by lvh** [comment]
#69 is already up; I'll open a second one to update the docs

**Comment by lvh** [comment]
I guess maybe CONTRIBUTING.md would be where that goes; would you like me to add those instructions somewhere or just not at all? (I obviously would have found `lein codox` by myself)

**Comment by ztellman** [comment]
Well, when everything is working properly I should be the only one generating the docs, I think.  Let's just update the dependencies and add instructions if that seems necessary.

**Comment by lvh** [comment]
Yeah; having the official docs being updated covers 95% of my use case for generating docs; and for the other 5% "do what the current codox readme says" should cover it :)

**Comment by lvh** [comment]
(Since the PR is up, I guess this ticket can be closed)
