### ISSUE TITLE
Retry Logic

### ISSUE THREAD

**Issue by derwolfe** [ztellman/manifold#71]
I've recently written some retry logic using `manifold.deferred` and `manifold.time` that uses exponential back off to retry asynchronous operations. The current implementation is available [here](https://github.com/derwolfe/cloudpassage-lib/blob/auth-error-handling/src/cloudpassage_lib/core.clj#L48-L86) and its tests are [here](https://github.com/derwolfe/cloudpassage-lib/blob/auth-error-handling/test/cloudpassage_lib/core_test.clj#L12-L54). 

Do you think this is something that you might like to integrate into manifold? If so, I'd be happy to open up and work on a PR.

**Comment by ztellman** [comment]
My knee-jerk reaction is that it's hard to create a "one true retry strategy" mechanism, and so I'd prefer to leave it as an implementation detail in applications.  If you strongly disagree, though, I'm willing to discuss it further.

**Comment by derwolfe** [comment]
I'm inclined to agree with you regarding the "one true retry strategy".  My main reason for suggesting was that it might form a helpful base for others. That being said,  a blog post showing how the logic was implemented might be more helpful :smile:. Thanks!
