### ISSUE TITLE
core.async chans can't be coerced to deferreds

### ISSUE THREAD

**Issue by lvh** [ztellman/manifold#72]
Example:

```
> (md/->deferred (clojure.core.async/chan))
IllegalArgumentException cannot convert clojure.core.async.impl.channels.ManyToManyChannel to deferred.  manifold.deferred/->deferred (deferred.clj:129)
> (md/->deferred (clojure.core.async/promise-chan))
IllegalArgumentException cannot convert clojure.core.async.impl.channels.ManyToManyChannel to deferred.  manifold.deferred/->deferred (deferred.clj:129)
```

`md/chain` appears to treat the chan as just another value:

```
> (md/chain (clojure.core.async/promise-chan) inc)
#<ErrorDeferred@7e9ead5e: ClassCastException clojure.core.async.impl.channels.ManyToManyChannel cannot be cast to java.lang.Number  clojure.lang.Numbers.inc (Numbers.java:112)
icecap.handlers.core> (md/chain (clojure.core.async/chan) inc)
#<ErrorDeferred@1625c143: ClassCastException clojure.core.async.impl.channels.ManyToManyChannel cannot be cast to java.lang.Number  clojure.lang.Numbers.inc (Numbers.java:112)
```

In all cases, I was expecting a deferred that would never fire (since the channel would never fire/close).

The [documentation][doc] claims otherwise:

> Values that can be coerced into a deferred include Clojure futures, Clojure promises, and core.async channels:

I don't know if the documentation is wrong or this is a bug. I could see how there's an impedance mismatch where you have to make sure the channel is closed before you can make the deferred fire?

[doc]: https://github.com/ztellman/manifold/blob/master/docs/deferred.md#composing-with-deferreds

**Comment by ztellman** [comment]
This was true, and then I decided it was weird to have both streams and deferreds being coercion targets for core.async.  The current method for coercion to a deferred is `(s/take! (s/->source chan))`.

**Comment by lvh** [comment]
Cool! I'll submit a PR.

**Comment by lvh** [comment]
Oops; I didn't realize you already resolved this. Thanks!
