### ISSUE TITLE
Items received in wrong order when connecting a stream and a core.async channel both ways

### ISSUE THREAD

**Issue by apa512** [ztellman/manifold#80]
```
(ns aleph-test.core
  (:require [manifold.stream :as s]
            [clojure.core.async :refer :all]))

(defn foo []
  (let [stream (s/stream)
        chan (chan)]
    (s/connect stream chan)
    (s/connect chan stream)
    (s/put-all! stream [1 2 3 4 5 6 7 8 9 10])
    (go-loop []
      (println (<! chan))
      (recur))))
=>
2
1
4
5
6
7
8
9
10
3
```
If I remove ```(s/connect chan stream)``` this works as expected with items put in the same order on the channel.

Is this supposed to work? My only reason for connecting the chan to the stream is to have the stream be closed when the channel is.

This is with ```[manifold "0.1.4"]``` but the latest alpha works the same.

**Comment by danielcompton** [comment]
I am probably reading this wrong as I'm very new to manifold, but it looks like you're connecting the stream to the chan, and then the chan back to the stream which would make a loop?

**Comment by ztellman** [comment]
Yeah, this will create an infinite loop, and you're just  reaching in there at random times to pull something out.  If you take out the second `connect`, everything should work as expected.
