### ISSUE TITLE
deferred/error! inside deferred/chain seems to not been catched

### ISSUE THREAD

**Issue by tangrammer** [ztellman/manifold#81]
Hi Manifold guys!
the [doc](https://github.com/ztellman/manifold/blob/master/docs/deferred.md) says that 
> If any stage in chain throws an exception or returns a deferred that yields an error, all subsequent stages are skipped, and the deferred returned by chain yields that same error. To handle these cases, you can use manifold.deferred/catch:

I'm trying that but i don't get the `b`error printed in my repl or nrepl ...

```clojure
(do
 (def a (d/deferred ))
      (def b (d/deferred ))
      (def c (d/deferred ))

      (-> (d/chain
	     a
	     (fn [a] (println "a=>" a) b)
	     (fn [b] (println "b=>" b) c)
	     (fn [c] (println "c=>" c) "YA")
	     (fn [x] (println "x=>" x))

          (d/catch Exception (fn [e]
                               (println (.getMessage e))
                               )))))


      (d/success! a "A")
    ;;  a=> A
    ;; true

      (d/error! b "B")
      ;; true
      ;; WHY DONT GET here the (println (.getMessage e)) ???


```

thanks in advance!

**Comment by ztellman** [comment]
You're trying to catch an Exception, but your error is just a String.
Manifold doesn't wrap your string in an Exception automatically, because
that would be very expensive. Either remove the Exception filter from
'catch', or pass an Exception into 'error!'.

**Comment by tangrammer** [comment]
That makes sense,
Thanks @ztellman for the quick answer!
