### ISSUE TITLE
Question: why does `stream/zip` need an intermediaries stream layer?

### ISSUE THREAD

**Issue by dm3** [ztellman/manifold#87]
I was wondering, why does the implementation of `manifold.stream/zip` create an [intermediary stream for each input stream](https://github.com/ztellman/manifold/blob/master/src/manifold/stream.clj#L649) instead of "zipping" the input streams directly?

**Comment by ztellman** [comment]
Because if loop/recur and connect based consumers are both given the same
stream, the loop/recur consumer may miss messages. Consider the case where
there are no intermediate streams, and we both map and zip over a
particular stream.

**Comment by dm3** [comment]
Makes sense, thanks!
