### ISSUE TITLE
[Question] What does it mean to be 'on' an executor?

### ISSUE THREAD

**Issue by arichiardi** [ztellman/manifold#88]
I see this line in the `instrumented-executor`:

> onto? if true, all streams and deferred generated in the scope of this executor will also be 'on' this executor.

Maybe my question is silly, but I would like to know what this technically means in case it is an useful feature :smile:

**Comment by ztellman** [comment]
This should explain it: http://aleph.io/manifold/execution.html

**Comment by arichiardi** [comment]
Yes that answers my question! Sorry for not having seen that doc earlier and thanks! Closing this one.
