### ISSUE TITLE
Unable to close stream with batch sink

### ISSUE THREAD

**Issue by ckarlsen84** [ztellman/manifold#90]
```clojure
(def a (s/stream))
(def b (s/batch 1024 100 a))

;; Hangs forever.
(s/close! a)
Evaluation interrupted.
=> nil
;; After manual interruption
(s/description a)
=>
{:pending-puts 0,
 :drained? true,
 :buffer-size 0,
 :permanent? false,
 :type "manifold",
 :sink? true,
 :closed? true,
 :pending-takes 0,
 :buffer-capacity 0,
 :source? true}

(s/description b)
=>
{:pending-puts 0,
 :drained? false,
 :buffer-size 0,
 :permanent? false,
 :type "manifold",
 :sink? true,
 :closed? false,
 :pending-takes 0,
 :buffer-capacity 0,
 :source? true}
```

Manifold 0.1.5 and Clojure 1.9.0-alpha10

**Comment by ztellman** [comment]
Thanks for the report, this is fixed as of `0.1.6-alpha1`.

**Comment by rborer** [comment]
Hi, I'm craving for this fix but I'm a bit afraid to use a version flagged as _alpha_, do you have any plan to release a stable manifold version soon? If not, I'll stick with 0.1.4 for now as it does not have this bug. Thanks 😄

**Comment by ztellman** [comment]
Yes, definitely planning a release, I'm sorry for the delay. I'll update
the issue once it's out.
