### ISSUE TITLE
Streams declare `IObj` but not `with-meta`

### ISSUE THREAD

**Issue by greglook** [ztellman/manifold#91]
Currently the types created by `manifold.stream.core/def-sink` and `def-source` declare that they implement [`clojure.lang.IObj`](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/IObj.java), but they don't actually implement the `with-meta` method that's part of the interface. I'm not sure if it makes sense to implement both `IObj` and `IReference`, since one is for mutable/stateful things and the other for immutable values - both pull in the general `meta` function from `IMeta`.

This is causing some issues with the `suspendable` library, which is trying to use `with-meta` to change the metadata on a stream used as a system component, causing an `AbstractMethodException`.

**Comment by ztellman** [comment]
It's been a while, but I think I meant to pull in `IMeta` and `IReference`, not `IObj`.  As you say, that's implicit, so I probably should have only used `IReference`.  This is a clear bug, and an easy fix.  Thanks for the report.
