### ISSUE TITLE
loop destructuring is not standard clojure destructuring

### ISSUE THREAD

**Issue by vspinu** [ztellman/manifold#98]
I cannot use `&` in loop bindings:

```clj
(d/loop [[a & b] [1 2 3]]
  [a b])
```

throws ` Unable to resolve symbol: & in this context`.

**Comment by lvh** [comment]
This can presumably be solved by using the (undocumented) `clojure.core/destructure`.

**Comment by ztellman** [comment]
That was my plan, but I've got sidetracked on my Strange Loop talk and haven't had a chance to implement it myself.  Pull requests welcome, etc.
